name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}

            # Remove old version if exists
            if [ -d "flask-deploy-demo" ]; then
              rm -rf flask-deploy-demo
            fi

            # Clone repo fresh
            git clone https://github.com/Ar-Aros/flask-deploy-demo
            cd flask-deploy-demo

            # Stop & remove old container if exists
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq '^flask-deploy-demo$'; then
              sudo docker stop flask-deploy-demo
              sudo docker rm flask-deploy-demo
            fi

            # Build Docker image
            if [ -f "Dockerfile" ]; then
              sudo docker build -t flask-deploy-demo .
            else
              echo "ERROR: Dockerfile not found!"
              exit 1
            fi

            # Run container
            sudo docker run -d -p 5000:5000 --name flask-deploy-demo flask-deploy-demo
