name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # Run workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}
            # Remove old version
            rm -rf flask-deploy-demo
            # Clone fresh code
            git clone https://github.com/<your-username>/<your-repo>.git flask-deploy-demo
            cd flask-deploy-demo
            # Stop old container if running
            sudo docker stop flask-deploy-demo || true
            sudo docker rm flask-deploy-demo || true
            # Build new Docker image
            sudo docker build -t flask-deploy-demo .
            # Run container
            sudo docker run -d -p 5000:5000 --name flask-deploy-demo flask-deploy-demo
